package com.tomasjimenez.ebankdo.hibernate.table;
// Generated by Hibernate Tools 3.2.1.GA

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


    private Integer coduser;
    private String username;
    private String password;

    public Users() {
    }

    public Users(String username, String password) {
       this.username = username;
       this.password = password;
    }

    /**
     * @return the coduser
     */
    public Integer getCoduser() {
        return coduser;
    }

    /**
     * @param coduser the coduser to set
     */
    public void setCoduser(Integer coduser) {
        this.coduser = coduser;
    }

    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }
   
   




}


